### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NycuRO** [AnkitM252/TransferPE#10]
Notice: Undefined variable: player in phar:///root/fac/plugins/phar_TransferPE-master_FsiE3asgVaz3ATM.phar/src/AnkitM252/Main.php on line 44
[Tesseract] [18:59:59] CRITICAL> Unhandled exception executing command 'hub' in hub: Call to a member function sendMessage() on null
[Tesseract] [18:59:59] CRITICAL> Error: "Call to a member function sendMessage() on null" (EXCEPTION) in "/plugins/phar_TransferPE-master_FsiE3asgVaz3ATM.phar/src/AnkitM252/Main" at line 44

@AnkitM252

**Comment by AnkitM252** [comment]
Fixed. Thanks for reporting!
