### ISSUE TITLE
it dosent worked Again

### ISSUE THREAD

**Issue by Pedramaps** [AnkitM252/TransferPE#14]
I tried last source but it dosent worked again. xD
What Can I Do? I Really Need A transfer plugin like this.

**Comment by AnkitM252** [comment]
It works fine for me and tge command usage is /transferpe <player name> <ip> <port>

**Comment by Pedramaps** [comment]
I know but how is it possible? It Said Your Transfered Successful but i dosent transfer to any where.
Can You Get Me A good mcpe source with support of this plugin?

**Comment by AnkitM252** [comment]
Was the server that you are trying is offline?

**Comment by Pedramaps** [comment]
No,That Was Lifeboat.

**Comment by AnkitM252** [comment]
I even tried on Lifeboat. It worked perfectly

**Comment by Pedramaps** [comment]
Hmm I Must Change Something In Server Configs? Or Vps Have Problems?

**Comment by AnkitM252** [comment]
Usage: /transferserver <player> <ip> <port>

**Comment by Pedramaps** [comment]
i dont have this command :(

**Comment by AnkitM252** [comment]
Its implemented in plugin itself!
