### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by AndreySK4** [AnkitM252/TransferPE#2]
I have this error at startup:
![_20170204_181406](https://cloud.githubusercontent.com/assets/17062704/22619840/f057369e-eb05-11e6-88d8-5831a6c4cccc.JPG)

I tested with PocketMine,Genisys,and Tesseract and at all I gived the error.

**Comment by Driesboy** [comment]
wait for the official 1.0.3 release please 
if they dont have a TransferPacket it will not work!

**Comment by AnkitM252** [comment]
Try with the latest source!
