### ISSUE TITLE
Error again

### ISSUE THREAD

**Issue by AndreySK4** [AnkitM252/TransferPE#4]
I have an error again:
[17:04:36] [Server thread/INFO]: Enabling TransferPE v1.0.0
[17:04:36] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Server::registerEvents()" (EXCEPTION) in "/plugins/TransferPE-master/src/AnkitM252/Main" at line 12
[17:04:36] [Server thread/INFO]: Disabling TransferPE v1.0.0
[17:04:36] [Server thread/INFO]: [TransferPE] TransferPE has been disabled!

**Comment by AnkitM252** [comment]
Oh got it sorry for the errors! Fixing now!

**Comment by AnkitM252** [comment]
Fixed! If any errors left send me here. So you don't have to make a new issue. I will not close it

**Comment by AndreySK4** [comment]
![screenshot_20170204-211530](https://cloud.githubusercontent.com/assets/17062704/22620909/26435328-eb1f-11e6-92ff-b229cf31ffd7.png)

**Comment by AnkitM252** [comment]
thanks again! fixed.
also very sorry for the errors..

**Comment by AndreySK4** [comment]
You are welcome

**Comment by AndreySK4** [comment]
![screenshot_20170205-100637](https://cloud.githubusercontent.com/assets/17062704/22624653/f2e6d8a8-eb8a-11e6-8f3d-2a3ec95a893b.png)

**Comment by AndreySK4** [comment]
[https://github.com/VentroxStudio/vTransfer](url)

This repository can help you ;)

**Comment by AnkitM252** [comment]
Fixed that too! I really don't need it cause but thanks for the suggestion.

**Comment by AndreySK4** [comment]
![_20170205_145624](https://cloud.githubusercontent.com/assets/17062704/22626314/710e2056-ebb3-11e6-92ee-242f23e6e5a5.JPG)

**Comment by AndreySK4** [comment]
I fixed the error from line 27,please accept my pull request

**Comment by AndreySK4** [comment]
After my modification,it doesn't me error,but doesn't transfer me.It's for MCPE 1.0.3 and above,right?

**Comment by AnkitM252** [comment]
yep its for 1.0.3+

**Comment by AnkitM252** [comment]
Is it working now?

**Comment by AnkitM252** [comment]
I forgot a main part of the plugin! So it was not transferring! thanks for the errors!
