### ISSUE TITLE
New plugin?

### ISSUE THREAD

**Issue by NycuRO** [AnkitM252/TransferPE#9]
You can create one plugin for "CombinedSlots"?

That plugin exist: https://github.com/HiddenMotives/CombinedSlots

But not work on Tesseract... :/

You can create? @AnkitM252

**Comment by AnkitM252** [comment]
I'll try but don't make a issue like this one! You can send me message on email or Twitter!
Closing this issue....
I'll try to make it!

**Comment by NycuRO** [comment]
@AnkitM252 Thanks <3

**Comment by NycuRO** [comment]
Thanks
